import { writeFileSync } from "fs";

// Comprehensive food database generator
// Each entry: [name, category, aliases[], fun_fact]

const foods = [
  // ═══════════════════════════════════════
  // FRUITS (80+)
  // ═══════════════════════════════════════
  ["apple", "fruit", ["apples", "green apple", "red apple", "granny smith", "fuji", "gala", "honeycrisp", "pink lady", "braeburn", "mcintosh"], "Apples float in water because they're 25% air."],
  ["banana", "fruit", ["bananas", "plantain", "plantains"], "Bananas are berries, but strawberries aren't."],
  ["orange", "fruit", ["oranges", "navel orange", "blood orange", "valencia orange", "cara cara"], "The color orange was named after the fruit, not the other way around."],
  ["strawberry", "fruit", ["strawberries", "strawberrys"], "Strawberries have their seeds on the outside — about 200 per berry."],
  ["blueberry", "fruit", ["blueberries", "blueberrys"], "Blueberries are one of the only naturally blue foods."],
  ["raspberry", "fruit", ["raspberries", "raspberrys"], "A single raspberry is made up of about 100 tiny individual fruits called drupelets."],
  ["blackberry", "fruit", ["blackberries", "blackberrys"], "Blackberries are technically not berries — they're aggregate fruits."],
  ["grape", "fruit", ["grapes", "green grapes", "red grapes", "concord grape", "table grapes"], "It takes about 2.5 pounds of grapes to make one bottle of wine."],
  ["watermelon", "fruit", ["watermelons", "water melon"], "Watermelon is 92% water and is related to cucumbers and pumpkins."],
  ["cantaloupe", "fruit", ["cantaloupes", "rockmelon", "rock melon", "muskmelon"], "Cantaloupe is named after the Italian town of Cantalupo."],
  ["honeydew", "fruit", ["honeydews", "honeydew melon", "honey dew"], "Honeydew melons are in the same family as cucumbers and squash."],
  ["pineapple", "fruit", ["pineapples", "ananas"], "A pineapple takes about two years to grow from planting to harvest."],
  ["mango", "fruit", ["mangos", "mangoes", "mangoe"], "Mangoes are the most consumed fruit in the world."],
  ["papaya", "fruit", ["papayas", "pawpaw", "paw paw"], "Papaya contains an enzyme called papain that can tenderize meat."],
  ["kiwi", "fruit", ["kiwis", "kiwifruit", "kiwi fruit", "chinese gooseberry"], "Kiwis have more vitamin C per ounce than oranges."],
  ["peach", "fruit", ["peaches", "nectarine", "nectarines"], "Peaches and nectarines are genetically almost identical — just one gene controls the fuzz."],
  ["plum", "fruit", ["plums", "prune", "prunes"], "Dried plums (prunes) were rebranded because the name 'prune' had an image problem."],
  ["cherry", "fruit", ["cherries", "cherrys", "bing cherry", "rainier cherry", "maraschino cherry", "sour cherry"], "It takes about 250 cherries to make a cherry pie."],
  ["apricot", "fruit", ["apricots"], "Apricots were first cultivated in China over 4,000 years ago."],
  ["pear", "fruit", ["pears", "bartlett pear", "bosc pear", "anjou pear"], "Pears ripen from the inside out, which is why they often feel soft near the core first."],
  ["lemon", "fruit", ["lemons"], "Lemons contain more sugar than strawberries."],
  ["lime", "fruit", ["limes", "key lime", "persian lime"], "British sailors earned the nickname 'limeys' because they ate limes to prevent scurvy."],
  ["grapefruit", "fruit", ["grapefruits", "grape fruit"], "Grapefruit can interact with over 85 medications."],
  ["tangerine", "fruit", ["tangerines", "mandarin", "mandarins", "clementine", "clementines", "satsuma", "satsumas"], "Tangerines are named after Tangier, Morocco, where they were first shipped to Europe."],
  ["pomegranate", "fruit", ["pomegranates", "pommegranate"], "A single pomegranate can contain over 600 seeds."],
  ["coconut", "fruit", ["coconuts", "cocoanut"], "Coconut water can be used as a substitute for blood plasma in emergencies."],
  ["avocado", "fruit", ["avocados", "avacado", "avacados", "guacamole"], "Avocados are technically berries, and they don't ripen on the tree."],
  ["fig", "fruit", ["figs"], "Figs are technically inverted flowers, not fruits."],
  ["date", "fruit", ["dates", "medjool date", "medjool dates", "deglet noor"], "Date palms can produce fruit for over 100 years."],
  ["guava", "fruit", ["guavas"], "Guava has four times the vitamin C of an orange."],
  ["passion fruit", "fruit", ["passion fruits", "passionfruit", "maracuja"], "Passion fruit is named after the Passion of Christ, not romantic passion."],
  ["lychee", "fruit", ["lychees", "litchi", "lichee"], "Lychee has been cultivated in China for over 2,000 years."],
  ["dragon fruit", "fruit", ["dragon fruits", "dragonfruit", "pitaya", "pitahaya"], "Dragon fruit comes from a cactus that only blooms at night."],
  ["starfruit", "fruit", ["starfruits", "star fruit", "carambola"], "Starfruit is one of the few fruits that's star-shaped when sliced."],
  ["persimmon", "fruit", ["persimmons"], "Unripe persimmons contain so much tannin they can make your mouth feel numb."],
  ["kumquat", "fruit", ["kumquats"], "Kumquats are the only citrus fruit you eat whole — skin and all."],
  ["jackfruit", "fruit", ["jackfruits", "jack fruit"], "Jackfruit is the largest tree-borne fruit in the world, weighing up to 80 pounds."],
  ["durian", "fruit", ["durians"], "Durian is banned on public transport in several Asian countries due to its smell."],
  ["mangosteen", "fruit", ["mangosteens"], "Mangosteen was once banned from import to the US because of fruit fly concerns."],
  ["rambutan", "fruit", ["rambutans"], "Rambutan means 'hairy' in Malay, referring to its spiky exterior."],
  ["cranberry", "fruit", ["cranberries", "cranberrys"], "Cranberries bounce when they're ripe — farmers use this to test quality."],
  ["boysenberry", "fruit", ["boysenberries"], "Boysenberries are a cross between raspberries, blackberries, and loganberries."],
  ["gooseberry", "fruit", ["gooseberries"], "Gooseberries were once banned in the US because they spread a disease that killed pine trees."],
  ["elderberry", "fruit", ["elderberries"], "Raw elderberries are actually toxic — they must be cooked before eating."],
  ["mulberry", "fruit", ["mulberries"], "Silkworms eat only mulberry leaves."],
  ["currant", "fruit", ["currants", "blackcurrant", "blackcurrants", "redcurrant", "redcurrants"], "Blackcurrants were banned in the US for nearly 100 years to protect pine trees."],
  ["quince", "fruit", ["quinces"], "Some historians believe the forbidden fruit in the Garden of Eden was a quince, not an apple."],
  ["tamarind", "fruit", ["tamarinds"], "Tamarind is a key ingredient in Worcestershire sauce."],
  ["breadfruit", "fruit", ["breadfruits", "bread fruit"], "When cooked, breadfruit has a texture and taste similar to freshly baked bread."],
  ["soursop", "fruit", ["soursops", "graviola"], "Soursop can weigh up to 15 pounds and has a flavor like strawberry-pineapple."],
  ["loquat", "fruit", ["loquats"], "Loquats are one of the few fruit trees that bloom in autumn and ripen in early spring."],
  ["plantain", "fruit", ["plantains"], "Plantains must be cooked before eating — they're starchier and less sweet than bananas."],
  ["cacao", "fruit", ["cocoa", "cacao bean", "cocoa bean", "cacao beans"], "It takes about 400 cacao beans to make one pound of chocolate."],
  ["acai", "fruit", ["acai berry", "acai berries", "açaí"], "Acai berries lose most of their antioxidant power within 24 hours of being picked."],
  ["goji berry", "fruit", ["goji berries", "wolfberry", "wolfberries"], "Goji berries have been used in traditional Chinese medicine for over 2,000 years."],
  ["yuzu", "fruit", ["yuzus"], "Yuzu is so prized in Japan that a single fruit can cost several dollars."],
  ["ugli fruit", "fruit", ["ugli fruits", "ugly fruit"], "Ugli fruit is a cross between a grapefruit, an orange, and a tangerine."],
  ["crabapple", "fruit", ["crabapples", "crab apple", "crab apples"], "All domestic apples are descended from wild crabapples."],
  ["damson", "fruit", ["damsons", "damson plum"], "Damsons have been grown in Britain since Roman times."],
  ["feijoa", "fruit", ["feijoas", "pineapple guava"], "Feijoa petals are edible and taste like cotton candy."],
  ["miracle fruit", "fruit", ["miracle fruits", "miracle berry"], "Miracle fruit makes sour foods taste sweet for up to an hour after eating it."],
  ["noni", "fruit", ["nonis", "noni fruit"], "Noni fruit smells so bad it's sometimes called 'vomit fruit.'"],
  ["rhubarb", "fruit", ["rhubarbs"], "Rhubarb leaves are poisonous, but the stalks are perfectly safe to eat."],
  ["salak", "fruit", ["salaks", "snake fruit"], "Salak is called 'snake fruit' because its skin looks like snake scales."],
  ["sapodilla", "fruit", ["sapodillas", "chikoo", "chiku"], "Sapodilla tree sap was the original base for chewing gum."],
  ["ackee", "fruit", ["ackees"], "Ackee is the national fruit of Jamaica but is toxic if eaten before it's fully ripe."],
  ["cherimoya", "fruit", ["cherimoyas", "custard apple", "custard apples"], "Mark Twain called cherimoya 'the most delicious fruit known to men.'"],
  ["horned melon", "fruit", ["horned melons", "kiwano", "kiwanos"], "Horned melon tastes like a combination of banana, cucumber, and lime."],
  ["jabuticaba", "fruit", ["jabuticabas"], "Jabuticaba fruits grow directly on the trunk of the tree, not on branches."],
  ["longan", "fruit", ["longans", "dragon eye"], "Longan means 'dragon eye' in Chinese because the fruit resembles an eyeball when peeled."],
  ["physalis", "fruit", ["ground cherry", "ground cherries", "cape gooseberry", "cape gooseberries"], "Physalis fruits come wrapped in their own papery lantern-like husk."],

  // ═══════════════════════════════════════
  // VEGETABLES (80+)
  // ═══════════════════════════════════════
  ["carrot", "vegetable", ["carrots", "carrott"], "Carrots were originally purple — orange carrots were bred in the Netherlands in the 17th century."],
  ["broccoli", "vegetable", ["brocolli", "brocoli", "broccolis"], "Broccoli is a human-engineered plant bred from wild cabbage."],
  ["cauliflower", "vegetable", ["cauliflowers", "cauliflour"], "Cauliflower comes in purple, green, and orange varieties, not just white."],
  ["spinach", "vegetable", ["spinachs"], "Spinach loses about 90% of its nutrients within 24 hours of being picked."],
  ["kale", "vegetable", ["kales", "curly kale"], "Kale was one of the most common green vegetables in Europe until the Middle Ages."],
  ["lettuce", "vegetable", ["lettuces", "romaine", "iceberg lettuce", "butterhead", "arugula", "rocket"], "Lettuce is a member of the sunflower family."],
  ["tomato", "vegetable", ["tomatoes", "tomatoe", "cherry tomato", "cherry tomatoes", "grape tomato", "heirloom tomato"], "Tomatoes were once considered poisonous in Europe and called 'poison apples.'"],
  ["potato", "vegetable", ["potatoes", "potatoe", "spud", "spuds", "tater", "taters"], "The potato was the first vegetable to be grown in space."],
  ["sweet potato", "vegetable", ["sweet potatoes", "sweetpotato", "yam", "yams"], "Sweet potatoes are not related to regular potatoes — they're in the morning glory family."],
  ["onion", "vegetable", ["onions", "red onion", "white onion", "yellow onion", "sweet onion", "vidalia"], "Onions make you cry because they release a sulfur-based gas when cut."],
  ["garlic", "vegetable", ["garlics", "garlic clove", "garlic cloves"], "There's a garlic festival in Gilroy, California that attracts over 100,000 people annually."],
  ["bell pepper", "vegetable", ["bell peppers", "capsicum", "sweet pepper", "sweet peppers", "red pepper", "green pepper", "yellow pepper"], "Green, yellow, and red bell peppers are actually the same vegetable at different stages of ripeness."],
  ["cucumber", "vegetable", ["cucumbers"], "Cucumbers are 96% water, making them one of the most hydrating foods."],
  ["zucchini", "vegetable", ["zucchinis", "courgette", "courgettes", "zuchini"], "The world's largest zucchini on record weighed over 65 pounds."],
  ["eggplant", "vegetable", ["eggplants", "aubergine", "aubergines", "brinjal"], "Eggplant is technically a berry and is related to tomatoes and tobacco."],
  ["celery", "vegetable", ["celerys", "celeries", "celery stalk", "celery stalks"], "Celery has negative calories — it takes more energy to digest than it contains."],
  ["asparagus", "vegetable", ["asparaguses", "asparagas"], "Asparagus can grow up to 10 inches in a single day."],
  ["corn", "vegetable", ["corns", "sweet corn", "maize", "corn on the cob"], "Each ear of corn has an even number of rows, typically 16."],
  ["pea", "vegetable", ["peas", "green peas", "garden peas", "snow pea", "snow peas", "sugar snap pea", "sugar snap peas"], "Gregor Mendel used pea plants to discover the laws of genetics."],
  ["green bean", "vegetable", ["green beans", "string bean", "string beans", "french bean", "french beans", "haricot vert"], "Green beans are picked before their seeds fully develop — that's why they're tender."],
  ["brussels sprout", "vegetable", ["brussels sprouts", "brussel sprouts", "brussel sprout"], "Brussels sprouts grow on a tall stalk, clustered like tiny cabbages."],
  ["cabbage", "vegetable", ["cabbages", "red cabbage", "green cabbage", "savoy cabbage", "napa cabbage"], "Ancient Romans believed eating cabbage before drinking would prevent drunkenness."],
  ["artichoke", "vegetable", ["artichokes"], "Artichokes are actually flower buds — if left unharvested, they bloom into purple flowers."],
  ["beet", "vegetable", ["beets", "beetroot", "beetroots"], "Beetroot juice was used as a natural dye for lips and cheeks in the Victorian era."],
  ["radish", "vegetable", ["radishes", "radishs", "daikon", "daikons"], "Radishes were paid as 'wages' to Egyptian pyramid builders."],
  ["turnip", "vegetable", ["turnips"], "Before pumpkins, people in Ireland carved turnips for Halloween jack-o'-lanterns."],
  ["parsnip", "vegetable", ["parsnips"], "Parsnips get sweeter after a frost because the cold converts their starch to sugar."],
  ["fennel", "vegetable", ["fennels"], "Marathon, the Greek city, was named after fennel — 'marathon' means 'place of fennel.'"],
  ["leek", "vegetable", ["leeks"], "The leek is the national emblem of Wales."],
  ["scallion", "vegetable", ["scallions", "green onion", "green onions", "spring onion", "spring onions"], "Scallions, green onions, and spring onions are all essentially the same thing."],
  ["shallot", "vegetable", ["shallots"], "Shallots grow in clusters like garlic rather than as single bulbs like onions."],
  ["chili pepper", "vegetable", ["chili peppers", "chilli", "chillis", "chillies", "hot pepper", "hot peppers", "jalapeno", "jalapenos", "habanero", "habaneros", "serrano", "cayenne"], "The heat of chili peppers comes from capsaicin, which birds can't taste at all."],
  ["okra", "vegetable", ["okras", "ladies finger", "lady finger", "ladyfinger", "gumbo"], "Okra pods can grow from flower to harvest-ready in just two days."],
  ["chard", "vegetable", ["chards", "swiss chard", "rainbow chard"], "Swiss chard has nothing to do with Switzerland — a Swiss botanist just named it."],
  ["collard greens", "vegetable", ["collards", "collard", "collard green"], "Collard greens have been cultivated for over 2,000 years."],
  ["bok choy", "vegetable", ["bok choys", "pak choi", "pak choy", "chinese cabbage"], "Bok choy has more calcium per ounce than milk."],
  ["watercress", "vegetable", ["watercresses"], "Watercress was eaten by Roman soldiers to give them strength and vigor."],
  ["endive", "vegetable", ["endives", "chicory", "escarole", "frisee"], "Endive is grown in darkness to keep it pale and reduce bitterness."],
  ["kohlrabi", "vegetable", ["kohlrabis", "kohl rabi"], "Kohlrabi means 'cabbage turnip' in German, though it tastes like neither."],
  ["rutabaga", "vegetable", ["rutabagas", "swede", "swedes", "neep", "neeps"], "Rutabaga is a cross between a cabbage and a turnip that occurred naturally."],
  ["jicama", "vegetable", ["jicamas"], "Jicama roots are edible but the rest of the plant, including the seeds, is toxic."],
  ["taro", "vegetable", ["taros", "taro root"], "Taro is one of the oldest cultivated crops, grown for over 10,000 years."],
  ["cassava", "vegetable", ["cassavas", "yuca", "manioc", "tapioca"], "Cassava is the third-largest source of carbohydrates in the tropics."],
  ["bamboo shoot", "vegetable", ["bamboo shoots", "bamboo"], "Bamboo is the fastest-growing plant on Earth, growing up to 35 inches per day."],
  ["water chestnut", "vegetable", ["water chestnuts"], "Water chestnuts aren't nuts — they're aquatic vegetables that grow in marshes."],
  ["celeriac", "vegetable", ["celery root"], "Celeriac is the same species as celery but bred for its root instead of its stalks."],
  ["butternut squash", "vegetable", ["butternut squashes", "butternut"], "Butternut squash was developed in Massachusetts in the 1940s."],
  ["acorn squash", "vegetable", ["acorn squashes"], "Acorn squash was a staple food for Native Americans long before European contact."],
  ["spaghetti squash", "vegetable", ["spaghetti squashes"], "When cooked, spaghetti squash flesh separates into noodle-like strands naturally."],
  ["pumpkin", "vegetable", ["pumpkins", "pumpkin squash"], "The heaviest pumpkin ever grown weighed over 2,700 pounds."],
  ["delicata squash", "vegetable", ["delicata squashes", "delicata"], "Delicata squash skin is edible, unlike most other winter squashes."],
  ["chayote", "vegetable", ["chayotes", "mirliton", "christophene"], "A chayote can sprout and grow a new plant while still sitting on your kitchen counter."],
  ["mushroom", "vegetable", ["mushrooms", "button mushroom", "cremini", "baby bella"], "Mushrooms are more closely related to humans than to plants."],
  ["yam", "vegetable", ["yams", "true yam"], "True yams can grow up to 5 feet long and weigh over 130 pounds."],
  ["horseradish", "vegetable", ["horseradishes"], "Horseradish releases its pungent oil only when the root cells are crushed or grated."],
  ["wasabi", "vegetable", ["wasabis"], "Real wasabi is so hard to grow that most 'wasabi' served is actually dyed horseradish."],
  ["ginger", "vegetable", ["gingers", "ginger root"], "Ginger has been used medicinally for over 5,000 years."],
  ["turmeric", "vegetable", ["turmerics", "turmeric root"], "Turmeric has been used as a dye for Buddhist monks' robes for centuries."],
  ["lotus root", "vegetable", ["lotus roots"], "Lotus roots have a beautiful hole pattern that allows air to travel to submerged parts of the plant."],
  ["hearts of palm", "vegetable", ["heart of palm", "palm heart", "palm hearts", "palmito"], "Harvesting hearts of palm from a single-stemmed palm kills the entire tree."],
  ["romanesco", "vegetable", ["romanescos", "romanesco broccoli"], "Romanesco grows in a perfect mathematical fractal pattern — each bud is a Fibonacci spiral."],
  ["broccoli rabe", "vegetable", ["broccoli rabi", "rapini", "broccolini"], "Broccoli rabe is more closely related to turnips than to broccoli."],
  ["daikon", "vegetable", ["daikons", "daikon radish", "white radish", "mooli"], "Daikon radishes can grow over 3 feet long and weigh up to 50 pounds."],
  ["edamame", "vegetable", ["edamames", "edamame beans"], "Edamame are immature soybeans picked before they harden."],
  ["snap pea", "vegetable", ["snap peas", "sugar snap", "sugar snaps"], "Snap peas were created in the 1970s by crossing garden peas with snow peas."],
  ["samphire", "vegetable", ["samphires", "sea asparagus", "glasswort"], "Samphire grows wild on coastal rocks and naturally tastes salty."],
  ["fiddlehead", "vegetable", ["fiddleheads", "fiddlehead fern"], "Fiddleheads are the curled fronds of young ferns, available for just a few weeks each spring."],
  ["nopales", "vegetable", ["nopal", "cactus paddle", "cactus paddles", "prickly pear cactus"], "Nopales are cactus paddles that have been a staple in Mexican cuisine for thousands of years."],
  ["sorrel", "vegetable", ["sorrels"], "Sorrel's tangy lemony flavor comes from oxalic acid, the same compound found in rhubarb."],

  // ═══════════════════════════════════════
  // GRAINS (30+)
  // ═══════════════════════════════════════
  ["rice", "grain", ["rices", "white rice", "brown rice", "basmati", "jasmine rice", "wild rice", "arborio", "sushi rice"], "Rice feeds more than half the world's population."],
  ["wheat", "grain", ["wheats", "whole wheat", "wheat berry", "wheat berries"], "Wheat was one of the first crops domesticated by humans, around 10,000 years ago."],
  ["oat", "grain", ["oats", "oatmeal", "rolled oats", "steel cut oats", "porridge", "oat groats"], "Oats are the only cereal grain that naturally contain a significant amount of fat."],
  ["barley", "grain", ["barleys", "pearl barley", "hulled barley"], "Barley was the standard unit of measurement in ancient Mesopotamia."],
  ["corn", "grain", ["corns", "maize", "cornmeal", "polenta", "grits", "hominy"], "An ear of corn always has an even number of rows."],
  ["quinoa", "grain", ["quinoas", "keen-wah"], "Quinoa is not actually a grain — it's a seed related to spinach and beets."],
  ["millet", "grain", ["millets", "finger millet", "pearl millet"], "Millet was the first domesticated cereal grain, predating rice and wheat."],
  ["sorghum", "grain", ["sorghums", "jowar", "milo"], "Sorghum is the fifth most important cereal crop in the world."],
  ["buckwheat", "grain", ["buckwheats", "kasha", "soba"], "Buckwheat isn't wheat at all — it's related to rhubarb."],
  ["rye", "grain", ["ryes", "rye grain"], "Rye can grow in poor soil and cold climates where other grains fail."],
  ["spelt", "grain", ["spelts"], "Spelt is an ancient grain that's been cultivated for over 7,000 years."],
  ["amaranth", "grain", ["amaranths"], "Amaranth was a staple food of the Aztecs, who mixed it with blood for religious ceremonies."],
  ["teff", "grain", ["teffs"], "Teff grains are so tiny that one grain is only 1/150th the size of a wheat kernel."],
  ["farro", "grain", ["farros", "emmer", "emmer wheat"], "Farro fed the Roman legions as they conquered the ancient world."],
  ["freekeh", "grain", ["freekahs", "freekah", "farik"], "Freekeh is green wheat that's been roasted while still young, giving it a smoky flavor."],
  ["kamut", "grain", ["kamuts", "khorasan wheat"], "Kamut grains are two to three times the size of modern wheat."],
  ["triticale", "grain", ["triticales"], "Triticale is a human-made grain — a cross between wheat and rye created in the 1800s."],
  ["couscous", "grain", ["couscouses"], "Couscous isn't a grain — it's tiny pasta made from semolina wheat."],
  ["bulgur", "grain", ["bulgurs", "bulgar", "bulgher", "cracked wheat"], "Bulgur is one of the fastest-cooking whole grains because it's already been parboiled."],
  ["semolina", "grain", ["semolinas"], "Semolina is the coarse flour used to make pasta, couscous, and many desserts."],
  ["cornmeal", "grain", ["corn meal", "polenta", "grits", "masa"], "Polenta was once considered peasant food in Italy but is now a gourmet staple."],
  ["einkorn", "grain", ["einkorns", "einkorn wheat"], "Einkorn is the oldest known variety of wheat, dating back 10,000 years."],
  ["tapioca", "grain", ["tapiocas", "tapioca pearls", "boba", "sago"], "Tapioca comes from cassava root and is the basis for boba tea pearls."],
  ["wild rice", "grain", ["wild rices"], "Wild rice isn't actually rice — it's the seed of an aquatic grass native to North America."],
  ["arborio rice", "grain", ["arborio"], "Arborio rice can absorb five times its weight in liquid, which is what makes risotto creamy."],
  ["jasmine rice", "grain", ["jasmine"], "Jasmine rice gets its floral aroma from a compound also found in pandan leaves and popcorn."],
  ["basmati rice", "grain", ["basmati"], "Aged basmati rice is considered superior — some varieties are aged for up to two years."],
  ["flaxseed meal", "grain", ["flax meal"], "Flaxseed meal was used by ancient Egyptians both as food and as a linen textile."],

  // ═══════════════════════════════════════
  // LEGUMES (25+)
  // ═══════════════════════════════════════
  ["lentil", "legume", ["lentils", "red lentil", "green lentil", "brown lentil", "black lentil", "puy lentil"], "Lentils are one of the oldest cultivated foods, dating back over 9,000 years."],
  ["chickpea", "legume", ["chickpeas", "garbanzo", "garbanzo bean", "garbanzo beans", "chana"], "Chickpeas are the most widely consumed legume in the world."],
  ["black bean", "legume", ["black beans", "turtle bean", "turtle beans"], "Black beans have as many antioxidants as grapes and cranberries."],
  ["kidney bean", "legume", ["kidney beans", "red kidney bean"], "Raw kidney beans contain a toxin that can cause severe nausea — always cook them first."],
  ["pinto bean", "legume", ["pinto beans"], "Pinto means 'painted' in Spanish, referring to the bean's speckled appearance."],
  ["navy bean", "legume", ["navy beans", "haricot bean", "haricot beans", "white bean", "white beans"], "Navy beans got their name because the US Navy served them as a staple food in the 1800s."],
  ["lima bean", "legume", ["lima beans", "butter bean", "butter beans"], "Lima beans are named after Lima, Peru, where they were first discovered by Europeans."],
  ["soybean", "legume", ["soybeans", "soya bean", "soya beans", "soya", "edamame"], "Soybeans are used to make everything from tofu to biodiesel fuel."],
  ["mung bean", "legume", ["mung beans", "moong bean", "moong", "green gram"], "Mung bean sprouts can grow 2-3 inches in just a few days."],
  ["adzuki bean", "legume", ["adzuki beans", "azuki", "azuki bean", "red bean", "red beans"], "In Japan, adzuki beans are used to make sweet red bean paste for desserts."],
  ["fava bean", "legume", ["fava beans", "broad bean", "broad beans"], "Pythagoras forbade his followers from eating fava beans for mysterious reasons."],
  ["green pea", "legume", ["green peas", "garden pea", "garden peas", "english pea", "english peas"], "The first peas were grown for their dried seeds, not eaten fresh like today."],
  ["split pea", "legume", ["split peas", "yellow split pea", "green split pea"], "Split peas are simply dried peas that have been peeled and split in half."],
  ["black-eyed pea", "legume", ["black-eyed peas", "cowpea", "cowpeas", "black eyed pea"], "Eating black-eyed peas on New Year's Day is a tradition believed to bring good luck."],
  ["pigeon pea", "legume", ["pigeon peas", "toor dal", "toor", "arhar"], "Pigeon peas can fix nitrogen in the soil, making them great for sustainable farming."],
  ["cannellini bean", "legume", ["cannellini beans", "white kidney bean", "white kidney beans"], "Cannellini beans are the most popular white bean in Italian cuisine."],
  ["cranberry bean", "legume", ["cranberry beans", "borlotti bean", "borlotti beans", "romano bean"], "Cranberry beans lose their beautiful speckled pattern when cooked."],
  ["great northern bean", "legume", ["great northern beans"], "Great northern beans are medium-sized white beans popular in French cassoulet."],
  ["lupini bean", "legume", ["lupini beans", "lupin bean", "lupin beans"], "Lupini beans must be soaked for days to remove their natural bitter alkaloids."],
  ["peanut", "legume", ["peanuts", "groundnut", "groundnuts", "goober"], "Peanuts aren't nuts — they're legumes that grow underground."],
  ["mesquite", "legume", ["mesquite bean", "mesquite beans", "mesquite flour"], "Mesquite pods were a primary food source for Native Americans in the Southwest."],
  ["carob", "legume", ["carobs", "carob bean", "carob powder"], "Carob seeds are so uniform in size they were used as the original carat weight for gemstones."],
  ["tamarind", "legume", ["tamarinds"], "Tamarind pod pulp is both sweet and sour and is used in cuisines across 5 continents."],
  ["alfalfa", "legume", ["alfalfa sprouts", "lucerne"], "Alfalfa roots can grow over 20 feet deep into the ground."],

  // ═══════════════════════════════════════
  // NUTS (15+)
  // ═══════════════════════════════════════
  ["almond", "nut", ["almonds", "almand"], "Almonds are seeds, not true nuts — they're related to peaches and plums."],
  ["walnut", "nut", ["walnuts", "english walnut", "black walnut"], "Walnut shells were used as explosives in World War II."],
  ["cashew", "nut", ["cashews", "cashew nut", "cashew nuts"], "Cashews grow hanging from the bottom of a cashew apple fruit."],
  ["pistachio", "nut", ["pistachios", "pistachio nut"], "Pistachios are sometimes called 'the smiling nut' in Iran and 'the happy nut' in China."],
  ["pecan", "nut", ["pecans"], "Pecans are the only major tree nut native to North America."],
  ["macadamia", "nut", ["macadamias", "macadamia nut", "macadamia nuts"], "Macadamia nuts have the hardest shell of any commercially sold nut."],
  ["hazelnut", "nut", ["hazelnuts", "filbert", "filberts", "cobnut"], "About 70% of the world's hazelnuts come from Turkey."],
  ["brazil nut", "nut", ["brazil nuts"], "Brazil nut trees can live for over 500 years and only grow in undisturbed rainforest."],
  ["chestnut", "nut", ["chestnuts", "sweet chestnut"], "Chestnuts are the only nuts that contain vitamin C."],
  ["pine nut", "nut", ["pine nuts", "pignoli", "pinoli", "pinon"], "It can take up to 25 years for a pine tree to start producing pine nut cones."],
  ["coconut", "nut", ["coconuts", "cocoanut"], "Coconuts are technically drupes, not nuts — and they can float across oceans to spread."],
  ["acorn", "nut", ["acorns"], "Acorns were a dietary staple for many Native American tribes for thousands of years."],
  ["kola nut", "nut", ["kola nuts", "cola nut", "cola nuts"], "Kola nuts were the original source of caffeine in Coca-Cola."],
  ["tiger nut", "nut", ["tiger nuts", "chufa"], "Tiger nuts aren't nuts at all — they're small root vegetables (tubers)."],
  ["candlenut", "nut", ["candlenuts", "kukui nut"], "Candlenuts are so oily they were literally burned as candles in ancient Hawaii."],
  ["marcona almond", "nut", ["marcona almonds"], "Marcona almonds are called the 'queen of almonds' and only grow in Spain."],
  ["mongongo nut", "nut", ["mongongo nuts"], "Mongongo nuts have been a staple food in southern Africa for over 7,000 years."],

  // ═══════════════════════════════════════
  // SEEDS (15+)
  // ═══════════════════════════════════════
  ["chia seed", "seed", ["chia seeds", "chia"], "Chia seeds can absorb up to 12 times their weight in water."],
  ["flaxseed", "seed", ["flaxseeds", "flax seed", "flax seeds", "linseed", "linseeds"], "Flaxseed was cultivated in Babylon as early as 3000 BC."],
  ["hemp seed", "seed", ["hemp seeds", "hemp hearts"], "Hemp seeds contain all 20 amino acids, including all 9 essential ones."],
  ["sunflower seed", "seed", ["sunflower seeds"], "A single sunflower head can contain up to 2,000 seeds."],
  ["pumpkin seed", "seed", ["pumpkin seeds", "pepita", "pepitas"], "Pumpkin seeds have been found in Mexican caves dating back over 7,000 years."],
  ["sesame seed", "seed", ["sesame seeds", "sesame", "tahini"], "Sesame may be the oldest condiment known to man, dating back to 3000 BC."],
  ["poppy seed", "seed", ["poppy seeds"], "Poppy seeds can cause a false positive on drug tests because they come from opium poppies."],
  ["fennel seed", "seed", ["fennel seeds"], "Roman gladiators ate fennel seeds believing they gave them strength and courage."],
  ["cumin seed", "seed", ["cumin seeds"], "Cumin is the second most popular spice in the world after black pepper."],
  ["coriander seed", "seed", ["coriander seeds"], "Coriander seeds have been found in ancient Egyptian tombs dating back 3,000 years."],
  ["caraway seed", "seed", ["caraway seeds", "caraway"], "Caraway seeds are the key flavoring in rye bread."],
  ["mustard seed", "seed", ["mustard seeds"], "It takes about 1,000 mustard seeds to make one tablespoon of prepared mustard."],
  ["nigella seed", "seed", ["nigella seeds", "black seed", "black seeds", "black cumin", "kalonji"], "Nigella seeds have been found in Tutankhamun's tomb and are called 'the seed of blessing.'"],
  ["sacha inchi", "seed", ["sacha inchi seeds", "inca nut", "inca peanut"], "Sacha inchi seeds contain more omega-3 than salmon."],
  ["watermelon seed", "seed", ["watermelon seeds"], "Roasted watermelon seeds are a popular snack in the Middle East and Asia."],
  ["lotus seed", "seed", ["lotus seeds"], "Lotus seeds have been germinated after lying dormant for over 1,000 years."],
  ["basil seed", "seed", ["basil seeds", "sabja", "tukmaria"], "Basil seeds swell up into a gel-like coating when soaked, similar to chia seeds."],

  // ═══════════════════════════════════════
  // MEATS (30+)
  // ═══════════════════════════════════════
  ["beef", "meat", ["beefs", "steak", "steaks", "ground beef", "mince", "brisket", "sirloin", "ribeye", "filet mignon", "t-bone", "chuck", "flank steak", "beef tenderloin"], "Beef from grass-fed cattle has a different fatty acid profile than grain-fed."],
  ["pork", "meat", ["porks", "pork chop", "pork chops", "bacon", "ham", "pork loin", "pork belly", "tenderloin", "pork shoulder", "pulled pork"], "Pork is the most widely consumed meat in the world."],
  ["lamb", "meat", ["lambs", "lamb chop", "lamb chops", "rack of lamb", "lamb shank", "leg of lamb", "mutton"], "Lamb under one year old is called lamb; over one year is called mutton."],
  ["veal", "meat", ["veals", "veal chop", "veal cutlet", "scallopini"], "Veal has been considered a delicacy since ancient Roman times."],
  ["venison", "meat", ["venisons", "deer meat", "deer"], "Venison comes from the Latin 'venari,' meaning 'to hunt.'"],
  ["bison", "meat", ["bisons", "buffalo meat", "buffalo"], "Bison meat has less fat and cholesterol than chicken breast."],
  ["rabbit", "meat", ["rabbits", "rabbit meat"], "Rabbit was the most commonly consumed meat in medieval Europe."],
  ["goat", "meat", ["goats", "goat meat", "chevon", "cabrito"], "Goat is the most widely consumed red meat globally."],
  ["elk", "meat", ["elks", "elk meat", "wapiti"], "Elk antlers can grow up to an inch per day, making them one of the fastest-growing bones."],
  ["wild boar", "meat", ["wild boars", "boar", "boar meat"], "Wild boar is the ancestor of all domestic pig breeds."],
  ["horse", "meat", ["horse meat", "horsemeat", "equine"], "Horse meat is a delicacy in many countries including France, Japan, and Kazakhstan."],
  ["kangaroo", "meat", ["kangaroo meat", "roo"], "Kangaroo meat is extremely lean, with less than 2% fat."],
  ["ostrich", "meat", ["ostrich meat"], "Ostrich meat looks and tastes more like beef than poultry despite being a bird."],
  ["alligator", "meat", ["alligator meat", "gator", "gator meat"], "Alligator meat tastes like a mild cross between chicken and fish."],
  ["frog legs", "meat", ["frog leg", "frogs legs", "frog"], "France consumes an estimated 80 million frogs per year."],
  ["prosciutto", "meat", ["prosciuttos"], "Authentic prosciutto di Parma takes at least 12 months to cure."],
  ["salami", "meat", ["salamis", "salame"], "Salami was invented as a way to preserve meat before refrigeration existed."],
  ["bresaola", "meat", ["bresaolas"], "Bresaola is air-dried beef that originated in the Lombardy region of Italy."],
  ["pancetta", "meat", ["pancettas"], "Pancetta is Italian bacon that's cured but not smoked."],
  ["chorizo", "meat", ["chorizos"], "Spanish and Mexican chorizo are completely different — Spanish is cured, Mexican is fresh."],
  ["corned beef", "meat", ["corned beefs"], "The 'corn' in corned beef refers to the large grains of salt used to cure it."],
  ["jerky", "meat", ["beef jerky", "turkey jerky", "jerkys", "biltong"], "Jerky comes from the Quechua word 'ch'arki,' meaning dried meat."],
  ["pastrami", "meat", ["pastramis"], "Pastrami was invented by Romanian Jews as a way to preserve goose meat."],
  ["sopressata", "meat", ["sopressatas", "soppressata"], "Sopressata is pressed flat during curing, which gives it its name and distinctive shape."],

  // ═══════════════════════════════════════
  // POULTRY (15+)
  // ═══════════════════════════════════════
  ["chicken", "poultry", ["chickens", "chicken breast", "chicken thigh", "chicken wing", "chicken drumstick", "chicken leg", "rotisserie chicken"], "There are more chickens on Earth than any other bird — about 25 billion."],
  ["turkey", "poultry", ["turkeys", "turkey breast", "ground turkey"], "Benjamin Franklin wanted the turkey, not the bald eagle, as America's national bird."],
  ["duck", "poultry", ["ducks", "duck breast", "duck leg", "peking duck", "duck confit"], "Ducks have waterproof feathers — even when they dive underwater, the downy layer stays dry."],
  ["goose", "poultry", ["geese", "goose breast", "goose leg"], "Geese mate for life and can live over 20 years."],
  ["quail", "poultry", ["quails", "quail breast"], "Quail eggs are considered a delicacy and have proportionally larger yolks than chicken eggs."],
  ["pheasant", "poultry", ["pheasants"], "Male pheasants are so colorful because they need to attract females who are plain brown."],
  ["guinea fowl", "poultry", ["guinea fowls", "guinea hen", "guinea hens"], "Guinea fowl are excellent at controlling tick populations."],
  ["cornish hen", "poultry", ["cornish hens", "cornish game hen", "cornish game hens", "poussin"], "Cornish hens aren't a separate breed — they're just young chickens harvested early."],
  ["squab", "poultry", ["squabs", "pigeon"], "Squab (young pigeon) was a common luxury food in ancient Egypt and Rome."],
  ["partridge", "poultry", ["partridges"], "The 'partridge in a pear tree' from the Christmas song is actually a red-legged partridge."],
  ["grouse", "poultry", ["grouses"], "The opening of grouse hunting season on August 12 is called 'The Glorious Twelfth' in Britain."],
  ["emu", "poultry", ["emus", "emu meat"], "Emu meat is very dark red, lean, and tastes similar to beef."],
  ["dove", "poultry", ["doves", "dove meat"], "Doves have been eaten as a game bird for thousands of years across the Mediterranean."],
  ["capon", "poultry", ["capons"], "A capon is a castrated rooster, which makes the meat more tender and flavorful."],

  // ═══════════════════════════════════════
  // FISH (40+)
  // ═══════════════════════════════════════
  ["salmon", "fish", ["salmons", "atlantic salmon", "pacific salmon", "sockeye", "chinook", "king salmon", "coho", "pink salmon", "lox", "smoked salmon"], "Salmon can jump up to 12 feet in the air to get past waterfalls."],
  ["tuna", "fish", ["tunas", "ahi tuna", "yellowfin tuna", "bluefin tuna", "albacore", "skipjack"], "A single bluefin tuna sold for $3.1 million at a Tokyo auction in 2019."],
  ["cod", "fish", ["cods", "atlantic cod", "pacific cod", "salt cod", "bacalao"], "Cod was so important to early American history that a wooden carving of one hangs in the Massachusetts State House."],
  ["tilapia", "fish", ["tilapias"], "Tilapia is one of the oldest farmed fish — ancient Egyptians raised them over 4,000 years ago."],
  ["halibut", "fish", ["halibuts"], "Halibut can weigh over 500 pounds and live for more than 50 years."],
  ["trout", "fish", ["trouts", "rainbow trout", "brown trout", "brook trout", "steelhead"], "Rainbow trout and steelhead are actually the same species — the difference is lifestyle."],
  ["bass", "fish", ["basses", "sea bass", "striped bass", "largemouth bass", "smallmouth bass", "chilean sea bass"], "Chilean sea bass was originally called 'Patagonian toothfish' until a fish dealer rebranded it."],
  ["sardine", "fish", ["sardines"], "Sardines are named after the Italian island of Sardinia, where they were once abundant."],
  ["anchovy", "fish", ["anchovies", "anchovys"], "Anchovies are the secret ingredient in Worcestershire sauce and Caesar dressing."],
  ["mackerel", "fish", ["mackerels", "king mackerel", "spanish mackerel"], "Mackerel can swim at speeds of up to 33 miles per hour."],
  ["swordfish", "fish", ["swordfishes"], "A swordfish's bill can reach temperatures of up to 80°F warmer than surrounding water."],
  ["mahi mahi", "fish", ["mahi-mahi", "dorado", "dolphinfish"], "Mahi mahi means 'strong strong' in Hawaiian."],
  ["snapper", "fish", ["snappers", "red snapper"], "Red snapper is so commonly mislabeled that studies found 73% of fish sold as snapper was something else."],
  ["grouper", "fish", ["groupers"], "Some grouper species can change sex from female to male as they age."],
  ["catfish", "fish", ["catfishes", "catfishs", "channel catfish"], "Catfish have over 100,000 taste buds — covering their entire body."],
  ["flounder", "fish", ["flounders"], "Flounder are born with eyes on both sides but one eye migrates as they grow."],
  ["sole", "fish", ["soles", "dover sole", "lemon sole"], "Dover sole was named after the English port of Dover where it was commonly landed."],
  ["haddock", "fish", ["haddocks"], "Haddock has a distinctive dark blotch on each side called 'Saint Peter's thumbprint.'"],
  ["pollock", "fish", ["pollocks", "pollack", "alaska pollock"], "Most imitation crab meat is actually made from pollock."],
  ["perch", "fish", ["perches", "yellow perch", "ocean perch"], "Perch are one of the most widely distributed freshwater fish in North America."],
  ["pike", "fish", ["pikes", "northern pike", "walleye"], "Northern pike can live over 25 years and have razor-sharp teeth."],
  ["monkfish", "fish", ["monkfishes"], "Monkfish is called 'poor man's lobster' because its tail meat has a similar texture."],
  ["barramundi", "fish", ["barramundis"], "Barramundi can change sex — they start as males and become females later in life."],
  ["branzino", "fish", ["branzinos", "european sea bass", "loup de mer"], "Branzino is one of the most popular fish in Mediterranean cuisine."],
  ["eel", "fish", ["eels", "unagi", "freshwater eel"], "No one has ever observed eels mating — their reproduction is one of nature's biggest mysteries."],
  ["herring", "fish", ["herrings", "kipper", "kippers", "pickled herring"], "Herring communicate by releasing bubbles from their rear end — scientists call it 'fast repetitive tick' sounds."],
  ["carp", "fish", ["carps", "common carp", "koi"], "Koi fish are just selectively bred carp that can live over 200 years."],
  ["whitefish", "fish", ["whitefishes", "lake whitefish"], "Whitefish is one of the most popular smoked fish in Jewish delicatessen cuisine."],
  ["wahoo", "fish", ["wahoos", "ono"], "Wahoo can swim at speeds up to 60 mph, making it one of the fastest fish in the ocean."],
  ["arctic char", "fish", ["arctic chars", "char"], "Arctic char is the most northerly freshwater fish in the world."],
  ["bluefish", "fish", ["bluefishes", "bluefish fillets"], "Bluefish are such aggressive predators they sometimes keep killing even after they're full."],
  ["pompano", "fish", ["pompanos", "florida pompano"], "Pompano is considered one of the finest eating fish in the Gulf of Mexico."],
  ["skate", "fish", ["skates", "skate wing"], "Skate wings develop a better flavor a day or two after being caught."],
  ["turbot", "fish", ["turbots"], "Turbot was so prized by the Romans that they had special diamond-shaped platters made for it."],
  ["john dory", "fish", ["john dorys", "st. peter's fish"], "John Dory has a distinctive dark spot on each side, said to be Saint Peter's thumbprint."],
  ["lingcod", "fish", ["lingcods"], "Lingcod sometimes have bright blue or green flesh, which turns white when cooked."],
  ["opah", "fish", ["opahs", "moonfish"], "Opah is the only known fully warm-blooded fish."],
  ["sturgeon", "fish", ["sturgeons", "beluga sturgeon"], "Sturgeons have been around for over 200 million years — they're older than dinosaurs."],
  ["cobia", "fish", ["cobias"], "Cobia have no swim bladder and must keep swimming to avoid sinking."],
  ["yellowtail", "fish", ["yellowtails", "hamachi", "yellowtail amberjack"], "Yellowtail hamachi is the most popular sushi fish in Japan."],

  // ═══════════════════════════════════════
  // SHELLFISH (20+)
  // ═══════════════════════════════════════
  ["shrimp", "shellfish", ["shrimps", "prawn", "prawns", "jumbo shrimp"], "A shrimp's heart is in its head."],
  ["crab", "shellfish", ["crabs", "crab meat", "crab legs", "king crab", "blue crab", "dungeness crab", "snow crab", "stone crab"], "Crabs' teeth are in their stomachs."],
  ["lobster", "shellfish", ["lobsters", "maine lobster", "rock lobster", "langoustine", "langoustines"], "Lobsters were once considered poverty food — prisoners and servants complained about eating them."],
  ["clam", "shellfish", ["clams", "littleneck", "cherrystone", "quahog", "geoduck", "manila clam"], "The oldest known animal ever was a clam named Ming, which lived to be 507 years old."],
  ["mussel", "shellfish", ["mussels", "green mussel", "blue mussel"], "Mussels attach to surfaces using incredibly strong threads called byssal threads."],
  ["oyster", "shellfish", ["oysters", "pacific oyster", "eastern oyster", "kumamoto"], "A single oyster can filter up to 50 gallons of water per day."],
  ["scallop", "shellfish", ["scallops", "bay scallop", "sea scallop", "diver scallop"], "Scallops have up to 200 tiny eyes that can detect movement and light."],
  ["squid", "shellfish", ["squids", "calamari"], "Squid have three hearts and blue blood."],
  ["octopus", "shellfish", ["octopuses", "octopi", "pulpo", "tako"], "Octopuses have three hearts, nine brains, and blue blood."],
  ["crawfish", "shellfish", ["crawfishes", "crayfish", "crawdad", "crawdads", "mudbug", "mudbugs", "yabby"], "Louisiana produces 90% of the crawfish consumed in the United States."],
  ["conch", "shellfish", ["conchs", "conch meat"], "Queen conch can live up to 30 years and grow shells up to 12 inches long."],
  ["abalone", "shellfish", ["abalones"], "Abalone shells are lined with nacre (mother of pearl), one of the strongest natural materials."],
  ["sea urchin", "shellfish", ["sea urchins", "uni"], "Sea urchin 'meat' (uni) is actually the animal's reproductive organs."],
  ["whelk", "shellfish", ["whelks"], "Whelks are predatory sea snails that drill holes through other shellfish to eat them."],
  ["periwinkle", "shellfish", ["periwinkles"], "Periwinkles are tiny sea snails commonly eaten as street food in Europe and Africa."],
  ["cuttlefish", "shellfish", ["cuttlefishes"], "Cuttlefish can change their skin color and texture in less than a second."],
  ["barnacle", "shellfish", ["barnacles", "goose barnacle", "percebes"], "Percebes (goose barnacles) are a delicacy in Spain that sell for over $100 per pound."],
  ["cockle", "shellfish", ["cockles"], "The phrase 'warming the cockles of your heart' refers to these heart-shaped shellfish."],
  ["razor clam", "shellfish", ["razor clams"], "Razor clams can burrow into sand at a rate of about one centimeter per second."],
  ["langoustine", "shellfish", ["langoustines", "dublin bay prawn", "norway lobster", "scampi"], "Langoustines are what most of Europe calls 'scampi.'"],

  // ═══════════════════════════════════════
  // DAIRY (30+)
  // ═══════════════════════════════════════
  ["milk", "dairy", ["milks", "whole milk", "skim milk", "2% milk", "buttermilk", "raw milk"], "Milk is the only food designed specifically to be food."],
  ["cheese", "dairy", ["cheeses"], "There are over 1,800 named varieties of cheese in the world."],
  ["cheddar", "dairy", ["cheddars", "cheddar cheese", "sharp cheddar", "mild cheddar"], "Cheddar cheese originated in the English village of Cheddar in Somerset."],
  ["mozzarella", "dairy", ["mozzarellas", "mozzarella cheese", "fresh mozzarella", "burrata"], "Real mozzarella di bufala is made from water buffalo milk, not cow's milk."],
  ["parmesan", "dairy", ["parmesans", "parmesan cheese", "parmigiano reggiano", "parmigiano"], "Authentic Parmigiano-Reggiano must be aged for at least 12 months."],
  ["brie", "dairy", ["bries", "brie cheese"], "Brie was called the 'king of cheeses' at a cheese competition in 1815."],
  ["gouda", "dairy", ["goudas", "gouda cheese", "aged gouda"], "Gouda accounts for 50-60% of all cheese consumed in the world."],
  ["feta", "dairy", ["fetas", "feta cheese"], "Under EU law, only cheese made in Greece from sheep's and goat's milk can be called feta."],
  ["swiss cheese", "dairy", ["swiss", "emmental", "emmentaler", "gruyere", "gruyère"], "The holes in Swiss cheese are caused by carbon dioxide released by bacteria during aging."],
  ["blue cheese", "dairy", ["blue cheeses", "bleu cheese", "roquefort", "gorgonzola", "stilton"], "Blue cheese gets its distinctive veins from Penicillium mold — the same genus as the antibiotic."],
  ["cream cheese", "dairy", ["cream cheeses", "philadelphia"], "Cream cheese was invented by accident by an American dairyman in 1872."],
  ["ricotta", "dairy", ["ricottas", "ricotta cheese"], "Ricotta means 'recooked' — it's made from whey left over from other cheese production."],
  ["cottage cheese", "dairy", ["cottage cheeses"], "Cottage cheese was likely the first cheese ever made in America."],
  ["goat cheese", "dairy", ["goat cheeses", "chevre", "chèvre"], "Goat cheese is easier to digest than cow's milk cheese for many people."],
  ["mascarpone", "dairy", ["mascarpones"], "Mascarpone is the key ingredient in tiramisu."],
  ["camembert", "dairy", ["camemberts", "camembert cheese"], "During World War I, camembert was issued to French soldiers as part of their rations."],
  ["halloumi", "dairy", ["halloumis", "haloumi"], "Halloumi has such a high melting point that you can grill or fry it like meat."],
  ["manchego", "dairy", ["manchegos", "manchego cheese"], "Authentic Manchego must be made from milk of Manchega sheep in La Mancha, Spain."],
  ["pecorino", "dairy", ["pecorinos", "pecorino romano"], "Pecorino Romano was part of the diet of Roman legionnaires 2,000 years ago."],
  ["provolone", "dairy", ["provolones"], "Provolone is hung from the ceiling to age, which is why it's often pear-shaped."],
  ["butter", "dairy", ["butters", "unsalted butter", "salted butter", "clarified butter", "ghee"], "It takes about 21 pounds of milk to make one pound of butter."],
  ["yogurt", "dairy", ["yogurts", "yoghurt", "yoghurts", "greek yogurt", "kefir", "skyr"], "Yogurt has been eaten for over 7,000 years."],
  ["cream", "dairy", ["creams", "heavy cream", "whipping cream", "double cream", "clotted cream", "sour cream", "creme fraiche"], "Clotted cream is made by slowly heating cream until it forms thick golden clots."],
  ["whey", "dairy", ["wheys", "whey protein"], "Whey was once discarded as waste until bodybuilders popularized whey protein supplements."],
  ["paneer", "dairy", ["paneers"], "Paneer doesn't melt because it's made by curdling milk with acid instead of rennet."],
  ["queso fresco", "dairy", ["queso frescos", "queso blanco"], "Queso fresco crumbles rather than melts, making it perfect as a topping."],
  ["havarti", "dairy", ["havartis"], "Havarti was invented in the 1800s by Hanne Nielsen on her farm in Denmark."],
  ["muenster", "dairy", ["muensters", "munster"], "The orange rind on Muenster cheese is colored with annatto, a natural plant dye."],
  ["limburger", "dairy", ["limburgers"], "Limburger is famous for its strong smell, which is caused by the same bacteria found on human skin."],
  ["asiago", "dairy", ["asiagos", "asiago cheese"], "Asiago has been made on the Asiago Plateau in Italy for over 1,000 years."],
  ["fontina", "dairy", ["fontinas", "fontina cheese"], "Fontina is one of Italy's great melting cheeses and is essential for fonduta."],

  // ═══════════════════════════════════════
  // EGGS (5+)
  // ═══════════════════════════════════════
  ["chicken egg", "egg", ["chicken eggs", "egg", "eggs", "hen egg", "hen eggs"], "A hen can lay about 300 eggs per year."],
  ["duck egg", "egg", ["duck eggs"], "Duck eggs have nearly twice the nutritional value of chicken eggs."],
  ["quail egg", "egg", ["quail eggs"], "Quail eggs are considered a remedy for allergies in several traditional medicine systems."],
  ["goose egg", "egg", ["goose eggs"], "A single goose egg is equivalent to about three chicken eggs."],
  ["ostrich egg", "egg", ["ostrich eggs"], "One ostrich egg equals about 24 chicken eggs and takes 2 hours to hard-boil."],
  ["turkey egg", "egg", ["turkey eggs"], "Turkey eggs are edible and delicious but rarely sold because turkeys lay far fewer than chickens."],
  ["caviar", "egg", ["caviars", "fish eggs", "fish roe", "roe", "tobiko", "ikura", "masago"], "Beluga caviar from the Caspian Sea can cost over $10,000 per kilogram."],

  // ═══════════════════════════════════════
  // HERBS (25+)
  // ═══════════════════════════════════════
  ["basil", "herb", ["basils", "sweet basil", "thai basil", "holy basil"], "In Italy, basil is a symbol of love — suitors traditionally give basil to their beloved."],
  ["cilantro", "herb", ["cilantros", "coriander", "coriander leaf", "chinese parsley"], "About 14% of people have a gene that makes cilantro taste like soap."],
  ["parsley", "herb", ["parsleys", "flat leaf parsley", "italian parsley", "curly parsley"], "Ancient Greeks used parsley to crown victors of athletic competitions."],
  ["mint", "herb", ["mints", "peppermint", "spearmint", "mentha"], "Mint is so invasive that gardeners are advised to grow it in containers to prevent it from taking over."],
  ["dill", "herb", ["dills"], "The word 'dill' comes from Old Norse 'dilla,' meaning 'to soothe.'"],
  ["rosemary", "herb", ["rosemarys", "rosemarys"], "Rosemary has been shown to improve memory — students in ancient Greece wore it during exams."],
  ["thyme", "herb", ["thymes"], "Ancient Egyptians used thyme for embalming their dead."],
  ["sage", "herb", ["sages", "common sage"], "The name 'sage' comes from the Latin 'salvare,' meaning 'to save' or 'to heal.'"],
  ["oregano", "herb", ["oreganos"], "Oregano only became popular in America after WWII soldiers brought a taste for it back from Italy."],
  ["chive", "herb", ["chives"], "Chives are the only allium species found growing wild on three continents."],
  ["tarragon", "herb", ["tarragons", "french tarragon"], "Tarragon was used in medieval times as a cure for snake bites."],
  ["bay leaf", "herb", ["bay leaves", "laurel leaf", "laurel leaves"], "Ancient Greeks and Romans crowned their heroes with wreaths of bay laurel leaves."],
  ["lemongrass", "herb", ["lemongrasses", "lemon grass"], "Lemongrass contains citral, the same compound that gives lemons their scent."],
  ["marjoram", "herb", ["marjorams", "sweet marjoram"], "Ancient Greeks believed marjoram was created by Aphrodite as a symbol of happiness."],
  ["lavender", "herb", ["lavenders"], "Lavender comes from the Latin 'lavare,' meaning 'to wash' — Romans added it to bath water."],
  ["chamomile", "herb", ["chamomiles", "camomile"], "Chamomile tea is one of the most widely consumed herbal teas in the world."],
  ["lemon balm", "herb", ["lemon balms", "melissa"], "Lemon balm has been cultivated for over 2,000 years to attract honeybees."],
  ["savory", "herb", ["savorys", "summer savory", "winter savory"], "Savory was used as a flavoring before pepper was widely available in Europe."],
  ["epazote", "herb", ["epazotes"], "Epazote is added to beans in Mexican cooking because it's believed to reduce gas."],
  ["curry leaf", "herb", ["curry leaves", "kadi patta"], "Curry leaves are not related to curry powder — they're from a completely different plant."],
  ["shiso", "herb", ["shisos", "perilla", "perilla leaf"], "Shiso comes in green and purple varieties and is a staple garnish in Japanese cuisine."],
  ["culantro", "herb", ["culantros", "sawtooth coriander", "long coriander", "ngo gai"], "Culantro looks nothing like cilantro but has 10 times stronger flavor."],
  ["woodruff", "herb", ["sweet woodruff"], "Woodruff is used to flavor May wine and German Waldmeister ice cream."],
  ["borage", "herb", ["borages"], "Borage flowers taste like cucumber and are used to garnish cocktails."],
  ["chervil", "herb", ["chervils"], "Chervil is one of the four herbs in the classic French 'fines herbes' blend."],
  ["lovage", "herb", ["lovages"], "Lovage tastes like a strong cross between celery and parsley."],

  // ═══════════════════════════════════════
  // SPICES (30+)
  // ═══════════════════════════════════════
  ["black pepper", "spice", ["black peppers", "pepper", "peppercorn", "peppercorns"], "In medieval Europe, black pepper was so valuable it was used as currency."],
  ["cinnamon", "spice", ["cinnamons", "ceylon cinnamon", "cassia"], "Most 'cinnamon' sold in stores is actually cassia, a related but cheaper spice."],
  ["turmeric", "spice", ["turmerics", "tumeric", "haldi"], "Turmeric's bright yellow color has been used as a fabric dye for centuries."],
  ["cumin", "spice", ["cumins", "jeera"], "Cumin seeds have been found in ancient Syrian archaeological sites dating back 4,000 years."],
  ["paprika", "spice", ["paprikas", "smoked paprika", "sweet paprika", "hot paprika"], "Paprika is the national spice of Hungary and is central to dishes like goulash."],
  ["ginger", "spice", ["gingers", "ground ginger", "ginger powder"], "Ginger can help reduce nausea and has been used as a natural remedy for motion sickness."],
  ["nutmeg", "spice", ["nutmegs"], "In the 1600s, nutmeg was so valuable that control of nutmeg islands sparked wars."],
  ["clove", "spice", ["cloves", "clovs"], "Cloves contain eugenol, a natural anesthetic — chewing one can numb a toothache."],
  ["cardamom", "spice", ["cardamoms", "cardamum", "elaichi"], "Cardamom is the third most expensive spice in the world, after saffron and vanilla."],
  ["saffron", "spice", ["saffrons"], "Saffron is the world's most expensive spice — it takes 75,000 flowers to make one pound."],
  ["vanilla", "spice", ["vanillas", "vanilla bean", "vanilla beans", "vanilla extract"], "Vanilla is the only edible fruit of the orchid family."],
  ["coriander", "spice", ["corianders", "coriander powder", "coriander seed"], "Coriander seeds and cilantro leaves come from the same plant but taste completely different."],
  ["chili powder", "spice", ["chili powders", "chile powder"], "Chili powder is actually a blend of spices, not just ground chilies."],
  ["cayenne", "spice", ["cayennes", "cayenne pepper"], "Cayenne pepper can temporarily boost metabolism by up to 20%."],
  ["allspice", "spice", ["allspices"], "Allspice is a single spice that tastes like a combination of cinnamon, nutmeg, and cloves."],
  ["star anise", "spice", ["star anises"], "Star anise is the source of shikimic acid, a key ingredient in the flu medication Tamiflu."],
  ["fenugreek", "spice", ["fenugreeks", "methi"], "Eating fenugreek can make your sweat and urine smell like maple syrup."],
  ["sumac", "spice", ["sumacs"], "Sumac was used as a souring agent in the Middle East long before lemons arrived from Asia."],
  ["za'atar", "spice", ["zaatar", "zatar"], "Za'atar is a blend of herbs and spices that has been eaten in the Middle East since ancient times."],
  ["five spice", "spice", ["five spice powder", "chinese five spice"], "Chinese five spice is designed to balance all five flavors: sweet, sour, bitter, salty, and umami."],
  ["mace", "spice", ["maces"], "Mace is the lacy red covering that surrounds the nutmeg seed — they're from the same fruit."],
  ["juniper berry", "spice", ["juniper berries"], "Juniper berries are the key flavoring ingredient in gin."],
  ["annatto", "spice", ["annattos", "achiote"], "Annatto gives Cheddar cheese, Velveeta, and even some butters their orange-yellow color."],
  ["grains of paradise", "spice", ["grains of paradice", "melegueta pepper"], "Grains of paradise were once used to flavor beer in medieval Europe before hops took over."],
  ["asafoetida", "spice", ["asafetida", "hing"], "Asafoetida smells terrible raw but becomes savory and onion-like when cooked."],
  ["szechuan pepper", "spice", ["szechuan peppercorn", "sichuan pepper", "sichuan peppercorn"], "Szechuan pepper creates a tingling, numbing sensation rather than heat."],
  ["white pepper", "spice", ["white peppers", "white peppercorn"], "White pepper is just black pepper with the outer layer removed."],
  ["pink peppercorn", "spice", ["pink peppercorns"], "Pink peppercorns aren't actually pepper — they're berries from a South American tree."],
  ["anise", "spice", ["anises", "aniseed"], "Anise is the flavor behind licorice, absinthe, and ouzo."],
  ["mustard powder", "spice", ["mustard powders", "dry mustard", "ground mustard"], "Mustard is one of the oldest known spices, with evidence of use dating back 5,000 years."],
  ["celery seed", "spice", ["celery seeds", "celery salt"], "Celery seed is a key ingredient in Old Bay seasoning."],

  // ═══════════════════════════════════════
  // OILS (10+)
  // ═══════════════════════════════════════
  ["olive oil", "oil", ["olive oils", "extra virgin olive oil", "EVOO", "virgin olive oil"], "It takes about 1,500 olives to make one liter of olive oil."],
  ["coconut oil", "oil", ["coconut oils"], "Coconut oil is one of the few plant-based sources of saturated fat."],
  ["sesame oil", "oil", ["sesame oils", "toasted sesame oil"], "Sesame oil was used as a cooking oil in ancient Babylon over 4,000 years ago."],
  ["avocado oil", "oil", ["avocado oils"], "Avocado oil has the highest smoke point of any unrefined oil."],
  ["sunflower oil", "oil", ["sunflower oils"], "Russia and Ukraine together produce over half the world's sunflower oil."],
  ["canola oil", "oil", ["canola oils", "rapeseed oil"], "Canola stands for 'Canadian oil, low acid' — it was developed in Canada."],
  ["peanut oil", "oil", ["peanut oils", "groundnut oil"], "Peanut oil is popular for deep frying because it doesn't absorb flavors from food."],
  ["walnut oil", "oil", ["walnut oils"], "Walnut oil was used by Renaissance painters like Leonardo da Vinci to thin paint."],
  ["grapeseed oil", "oil", ["grapeseed oils", "grape seed oil"], "Grapeseed oil is made from the seeds left over after wine production."],
  ["flaxseed oil", "oil", ["flaxseed oils", "linseed oil"], "Flaxseed oil has the highest omega-3 content of any plant oil."],
  ["truffle oil", "oil", ["truffle oils"], "Most truffle oil contains no actual truffles — it's made with a synthetic chemical."],
  ["hemp oil", "oil", ["hemp oils", "hemp seed oil"], "Hemp oil has the ideal 3:1 ratio of omega-6 to omega-3 fatty acids."],
  ["macadamia oil", "oil", ["macadamia oils"], "Macadamia oil has the highest monounsaturated fat content of any oil."],
  ["rice bran oil", "oil", ["rice bran oils"], "Rice bran oil is the most popular cooking oil in Japan and much of Asia."],

  // ═══════════════════════════════════════
  // SWEETENERS (10+)
  // ═══════════════════════════════════════
  ["honey", "sweetener", ["honeys", "raw honey", "manuka honey", "wildflower honey"], "Honey never spoils — 3,000-year-old honey from Egyptian tombs was still edible."],
  ["maple syrup", "sweetener", ["maple syrups", "maple syrop"], "It takes about 40 gallons of maple sap to make just one gallon of maple syrup."],
  ["agave", "sweetener", ["agaves", "agave nectar", "agave syrup"], "Agave is the same plant used to make tequila."],
  ["molasses", "sweetener", ["molassess", "blackstrap molasses", "treacle"], "The Great Molasses Flood of 1919 killed 21 people when a tank burst in Boston."],
  ["coconut sugar", "sweetener", ["coconut sugars", "palm sugar", "coconut palm sugar"], "Coconut sugar comes from the sap of coconut flower buds, not the coconut itself."],
  ["date syrup", "sweetener", ["date syrups", "date molasses", "silan"], "Date syrup has been used as a sweetener in the Middle East for over 5,000 years."],
  ["stevia", "sweetener", ["stevias", "stevia leaf"], "Stevia is up to 300 times sweeter than sugar but has zero calories."],
  ["monk fruit", "sweetener", ["monk fruits", "luo han guo"], "Monk fruit has been used as a sweetener in China for hundreds of years."],
  ["brown rice syrup", "sweetener", ["brown rice syrups", "rice syrup", "rice malt"], "Brown rice syrup is made by breaking down the starch in cooked rice with enzymes."],
  ["birch syrup", "sweetener", ["birch syrups"], "Birch syrup requires 100 gallons of sap to make one gallon — 2.5x more than maple."],
  ["muscovado sugar", "sweetener", ["muscovado sugars", "muscovado"], "Muscovado is the least refined form of cane sugar, retaining all its original molasses."],
  ["jaggery", "sweetener", ["jaggerys", "gur", "panela", "piloncillo"], "Jaggery is unrefined cane sugar used across South Asia, Africa, and Latin America."],

  // ═══════════════════════════════════════
  // FERMENTED (15+)
  // ═══════════════════════════════════════
  ["kimchi", "fermented", ["kimchis", "kimchee"], "There are over 200 varieties of kimchi in Korea."],
  ["sauerkraut", "fermented", ["sauerkrauts"], "Sauerkraut was brought on long sea voyages to prevent scurvy — it's rich in vitamin C."],
  ["miso", "fermented", ["misos", "miso paste"], "Some miso pastes are aged for over three years to develop deep, complex flavors."],
  ["tempeh", "fermented", ["tempehs", "temphe"], "Tempeh originated in Java, Indonesia, over 300 years ago."],
  ["kombucha", "fermented", ["kombuchas"], "Kombucha is fermented using a SCOBY — a symbiotic culture of bacteria and yeast."],
  ["tofu", "fermented", ["tofus", "bean curd", "silken tofu", "firm tofu"], "Tofu was invented in China over 2,000 years ago, possibly by accident."],
  ["soy sauce", "fermented", ["soy sauces", "shoyu", "tamari"], "Traditional soy sauce takes 6 months to 2 years to ferment."],
  ["fish sauce", "fermented", ["fish sauces", "nam pla", "nuoc mam"], "Ancient Romans had their own version of fish sauce called 'garum.'"],
  ["natto", "fermented", ["nattos"], "Natto is so sticky that it forms long, stringy threads when pulled apart."],
  ["kefir", "fermented", ["kefirs", "water kefir"], "Kefir grains are not actually grains — they're living symbiotic cultures."],
  ["sourdough", "fermented", ["sourdoughs", "sourdough bread", "sourdough starter"], "Some sourdough starters have been kept alive and fed for over 100 years."],
  ["pickles", "fermented", ["pickle", "gherkin", "gherkins", "dill pickle", "dill pickles"], "Cleopatra attributed her beauty to eating pickles."],
  ["vinegar", "fermented", ["vinegars", "apple cider vinegar", "balsamic vinegar", "rice vinegar", "red wine vinegar"], "Balsamic vinegar from Modena can be aged for over 25 years."],
  ["yogurt", "fermented", ["yogurts", "yoghurt", "leben", "lassi"], "The word 'yogurt' comes from Turkish and means 'to thicken.'"],
  ["preserved lemon", "fermented", ["preserved lemons", "lemon confit"], "Preserved lemons are a staple in Moroccan cuisine, adding intense citrus flavor."],
  ["injera", "fermented", ["injeras"], "Injera bread is naturally fermented for 2-3 days, giving it a slightly sour taste."],
  ["kvass", "fermented", ["kvasses"], "Kvass is a fermented bread drink that's been popular in Russia for over 1,000 years."],
  ["tepache", "fermented", ["tepaches"], "Tepache is a Mexican fermented drink made from pineapple rinds and spices."],

  // ═══════════════════════════════════════
  // FUNGI (15+)
  // ═══════════════════════════════════════
  ["button mushroom", "fungi", ["button mushrooms", "white mushroom", "white mushrooms", "cremini", "creminis", "baby bella", "baby bellas"], "Button mushrooms, cremini, and portobello are all the same species at different stages of growth."],
  ["portobello", "fungi", ["portobellos", "portobella", "portobello mushroom"], "Portobellos are just mature cremini mushrooms that have been allowed to grow larger."],
  ["shiitake", "fungi", ["shiitakes", "shiitake mushroom", "shiitake mushrooms"], "Shiitake mushrooms have been cultivated in Japan for over 1,000 years."],
  ["oyster mushroom", "fungi", ["oyster mushrooms"], "Oyster mushrooms are one of the few carnivorous mushrooms — they trap and digest tiny worms."],
  ["chanterelle", "fungi", ["chanterelles"], "Chanterelles cannot be commercially cultivated — they must be wild foraged."],
  ["porcini", "fungi", ["porcinis", "porcini mushroom", "cep", "ceps", "penny bun"], "Porcini means 'little pigs' in Italian."],
  ["morel", "fungi", ["morels", "morel mushroom"], "Morels appear only in spring and can sell for over $30 per pound."],
  ["truffle", "fungi", ["truffles", "black truffle", "white truffle", "truffle mushroom"], "White truffles from Alba, Italy, have sold for over $300,000 at auction."],
  ["enoki", "fungi", ["enokis", "enoki mushroom", "enoki mushrooms"], "Wild enoki mushrooms look completely different from the cultivated ones sold in stores."],
  ["maitake", "fungi", ["maitakes", "maitake mushroom", "hen of the woods"], "Maitake means 'dancing mushroom' — foragers supposedly danced with joy upon finding them."],
  ["king trumpet", "fungi", ["king trumpet mushroom", "king trumpets", "king oyster", "eryngii"], "King trumpet mushrooms are the largest species in the oyster mushroom family."],
  ["lions mane", "fungi", ["lions manes", "lion's mane", "lion's mane mushroom", "hericium"], "Lion's mane mushroom may stimulate nerve growth factor production in the brain."],
  ["wood ear", "fungi", ["wood ears", "wood ear mushroom", "black fungus", "cloud ear"], "Wood ear mushrooms are used in traditional Chinese medicine to improve blood circulation."],
  ["matsutake", "fungi", ["matsutakes", "matsutake mushroom"], "Matsutake mushrooms are so prized in Japan they're given as luxury gifts."],
  ["reishi", "fungi", ["reishis", "reishi mushroom", "lingzhi"], "Reishi is called the 'mushroom of immortality' in traditional Chinese medicine."],
  ["chaga", "fungi", ["chagas", "chaga mushroom"], "Chaga looks like a chunk of burnt charcoal growing on birch trees."],
  ["hedgehog mushroom", "fungi", ["hedgehog mushrooms", "pied de mouton"], "Hedgehog mushrooms have tiny spines instead of gills underneath their caps."],
  ["black trumpet", "fungi", ["black trumpets", "horn of plenty"], "Black trumpet mushrooms are also called 'trompette de la mort' (trumpet of death) despite being delicious."],

  // ═══════════════════════════════════════
  // SEAWEED (8+)
  // ═══════════════════════════════════════
  ["nori", "seaweed", ["noris"], "Nori was so valuable in ancient Japan that it was accepted as tax payment."],
  ["kelp", "seaweed", ["kelps", "giant kelp", "bull kelp"], "Giant kelp can grow up to 2 feet per day, making it one of the fastest-growing organisms."],
  ["wakame", "seaweed", ["wakames"], "Wakame is considered an invasive species in many countries outside Asia."],
  ["dulse", "seaweed", ["dulses"], "When fried, dulse tastes remarkably similar to bacon."],
  ["spirulina", "seaweed", ["spirulinas"], "Spirulina was a dietary staple of the Aztecs and is now studied as food for astronauts."],
  ["chlorella", "seaweed", ["chlorellas"], "Chlorella reproduces so quickly it can quadruple its cell count in less than a day."],
  ["kombu", "seaweed", ["kombus", "konbu"], "Kombu is naturally rich in glutamate, which is why it's used to make dashi broth so savory."],
  ["hijiki", "seaweed", ["hijikis"], "Hijiki has been a part of the Japanese diet for centuries and is traditionally served on holidays."],
  ["irish moss", "seaweed", ["irish mosses", "carrageen", "sea moss"], "Irish moss produces carrageenan, a thickener found in everything from ice cream to toothpaste."],
  ["agar", "seaweed", ["agars", "agar agar", "kanten"], "Agar is used as a vegetarian substitute for gelatin and was discovered by accident in Japan in the 1650s."],
  ["arame", "seaweed", ["arames"], "Arame has a mild, semi-sweet flavor that makes it one of the most approachable seaweeds."],
  ["sea lettuce", "seaweed", ["sea lettuces", "ulva"], "Sea lettuce is one of the most widely distributed seaweeds, found on every ocean coast."],

  // ═══════════════════════════════════════
  // BEVERAGES (15+)
  // ═══════════════════════════════════════
  ["tea", "beverage", ["teas", "green tea", "black tea", "white tea", "oolong", "herbal tea", "chai", "matcha", "earl grey", "english breakfast"], "All true tea comes from the same plant — Camellia sinensis."],
  ["coffee", "beverage", ["coffees", "espresso", "cappuccino", "latte", "americano", "cold brew", "drip coffee"], "Coffee was discovered by an Ethiopian goat herder who noticed his goats dancing after eating coffee berries."],
  ["cocoa", "beverage", ["hot chocolate", "hot cocoa", "drinking chocolate", "cacao drink"], "The Aztecs drank chocolate as a bitter, spicy beverage — sugar was added later by Europeans."],
  ["orange juice", "beverage", ["oj", "fresh squeezed orange juice"], "Florida produces about 70% of the United States' total orange juice supply."],
  ["apple juice", "beverage", ["apple juices", "apple cider"], "Unpasteurized apple cider was one of the most popular beverages in colonial America."],
  ["lemonade", "beverage", ["lemonades"], "The first recorded lemonade was sold in Paris in 1630 as a mix of sparkling water, lemon juice, and honey."],
  ["coconut water", "beverage", ["coconut waters"], "Coconut water is sterile inside the coconut and was used as IV fluid in emergencies."],
  ["pomegranate juice", "beverage", ["pomegranate juices"], "Pomegranate juice has more antioxidants than red wine or green tea."],
  ["cranberry juice", "beverage", ["cranberry juices"], "Native Americans used cranberries to dye fabric and as a poultice for wounds."],
  ["ginger beer", "beverage", ["ginger beers", "ginger ale"], "Original ginger beer was actually alcoholic — the modern soft drink version came later."],
  ["horchata", "beverage", ["horchatas"], "Horchata varies by country — in Mexico it's made from rice, in Spain from tiger nuts."],
  ["yerba mate", "beverage", ["yerba mates", "mate", "maté"], "Yerba mate contains caffeine and is traditionally shared from a single gourd with a metal straw."],
  ["rooibos", "beverage", ["rooibos tea", "red bush tea", "redbush"], "Rooibos only grows in a small region of South Africa and nowhere else on Earth."],
  ["hibiscus tea", "beverage", ["hibiscus teas", "agua de jamaica", "roselle"], "Hibiscus tea is bright red, naturally tart, and drunk across dozens of cultures worldwide."],
  ["beet juice", "beverage", ["beet juices", "beetroot juice"], "Beet juice can temporarily improve athletic performance by up to 3%."],
  ["wheatgrass juice", "beverage", ["wheatgrass juices", "wheatgrass"], "One ounce of wheatgrass juice is nutritionally equivalent to about 2.5 pounds of vegetables."],
  ["bone broth", "beverage", ["bone broths"], "Bone broth has been a staple of traditional diets for thousands of years across virtually every culture."],
];

const jsonOutput = foods.map(([name, category, aliases, fun_fact]) => ({
  name,
  category,
  aliases,
  fun_fact,
}));

writeFileSync(
  "/Users/marc/Documents/OwnProjects/FoodOrTrash/foodortrash/src/data/foods.json",
  JSON.stringify(jsonOutput, null, 2),
  "utf-8"
);

console.log(`Generated ${jsonOutput.length} food items.`);

// Print category breakdown
const counts = {};
for (const item of jsonOutput) {
  counts[item.category] = (counts[item.category] || 0) + 1;
}
console.log("\nCategory breakdown:");
for (const [cat, count] of Object.entries(counts).sort((a, b) => b[1] - a[1])) {
  console.log(`  ${cat}: ${count}`);
}
